INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Maria Oliveira', 'mariaoliveira@gmail.com', '71988887777', 'Construção irregular', 'Obra irregular', 'Obra está causando barulho e sujeira excessiva.', 'Augustinho do Amaral, 150, São Sebastião do Passé - BA', false);
INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Carlos Santos', 'carlossantos@hotmail.com', '71977776666', 'Descarte de lixo ilegal', 'Poluição', 'Lixo jogado em terreno baldio próximo ao bairro.', 'Travessa Pedro Francisco Telles, 45, São Sebastião do Passé - BA', true);
INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Ana Paula', 'anapaula@gmail.com', '71966665555', 'Falta de iluminação', 'Segurança pública', 'Rua muito escura, perigosa para pedestres à noite.', 'Rua da Malhada, 200, São Sebastião do Passé - BA', false);
INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Roberto Lima', 'robertolima@outlook.com', '71955554444', 'Árvores cortadas indevidamente', 'Meio ambiente', 'Cortaram árvores sem autorização na praça local.', 'Praça da Matriz, s/n, São Sebastião do Passé - BA', true);
INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Fernanda Souza', 'fernandasouza@gmail.com', '71944443333', 'Rachaduras em prédio', 'Risco estrutural', 'Apareceram rachaduras no prédio residencial.', 'Av. Hernane Oliveira Rocha, 77, São Sebastião do Passé - BA', false);
INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Marcos Paulo', 'marcospaulo@hotmail.com', '71933332222', 'Poluição sonora', 'Perturbação do sossego', 'Música alta em bar próximo até altas horas.', 'Rua Maria da Paz Ribeiro, 150, São Sebastião do Passé - BA', true);
INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Patrícia Reis', 'patriciareis@gmail.com', '71922221111', 'Calçada quebrada', 'Infraestrutura urbana', 'Calçada está quebrada e perigosa para pedestres.', 'Rua do Ezequiel, 333, São Sebastião do Passé - BA', false);
INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Eduardo Martins', 'eduardomartins@outlook.com', '71911110000', 'Trânsito desorganizado', 'Trânsito', 'Semáforo está quebrado e causa acidentes.', 'Rua IV Etapa Urbis, 800, São Sebastião do Passé - BA', true);
INSERT INTO denuncias (nome_usuario, email, telefone_usuario, titulo_denuncia, categoria_denuncia, descricao_denuncia, endereco_denuncia, denuncia_anonima) VALUES ('Juliana Costa', 'julianacosta@gmail.com', '71999998888', 'Vazamento de água', 'Serviço público', 'Vazamento constante na rua principal do bairro.', 'Centro, 45, São Sebastião do Passé - BA', false);
